name: my_flutter_sdk
description: A new Flutter module.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Añade otras dependencias aquí

flutter:
  module:
    androidX: true
    androidPackage: com.example.my_flutter_sdk
    iosBundleIdentifier: com.example.myFlutterSdk